version: '3.8'

services:
  db:
    image: postgres:15
    container_name: karoka_postgres_dev
    environment:
      POSTGRES_USER: karoka
      POSTGRES_PASSWORD: karoka
      POSTGRES_DB: karoka_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    env_file:
    - ./backend/.env
  

  backend:
    build:
      context: .
      dockerfile: infra/docker/backend.Dockerfile
    depends_on:
      - db
    env_file:
      - ./backend/.env   # contains secrets, config; does not need PORT unless you want to override
    environment:
      - DATABASE_URL=postgresql://karoka:karoka@db:5432/karoka_dev
      - FLASK_ENV=development
      - PORT=5001        # override default if you like; must match ports mapping
    ports:
      - "5001:5001"
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
      - ./backend/karoka-core-firebase-adminsdk.json:/app/backend/karoka-core-firebase-adminsdk.json

  frontend:
    build:
      context: .
      dockerfile: infra/docker/frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./apps/frontend:/app 
      - /app/node_modules 

    env_file:
    - ./apps/frontend/.env
    command: npm run dev

volumes:
  postgres_dev_data:
