# Generated by Django 5.1.3 on 2024-11-25 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="competition",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="puzzles",
                to="core.competition",
            ),
            preserve_default=False,
        ),
    ]
