# Generated by Django 5.1.3 on 2024-11-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
