# Generated by Django 5.1.3 on 2024-11-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_puzzle_userprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="answer",
            field=models.CharField(max_length=20),
        ),
    ]
