# Generated by Django 5.1.3 on 2024-11-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_userprogress_puzzle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="puzzle",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="core.puzzle",
            ),
        ),
    ]
