# Generated by Django 5.1.3 on 2024-11-25 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_puzzle_competition"),
        ("core", "0008_alter_userprogress_puzzle"),
    ]

    operations = []
