# Generated by Django 5.1.3 on 2024-11-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_competition_alter_puzzle_competition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
