# Generated by Django 5.1.3 on 2024-11-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_competition"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="story",
            field=models.TextField(blank=True, null=True),
        ),
    ]
