from pydantic import BaseModel, Field
from typing import Optional, Dict, Any
from datetime import datetime
import uuid

class AttemptBase(BaseModel):
    """
    Base Pydantic schema for an attempt. Contains all common fields.
    """
    puzzle_id: str
    start_ts: datetime
    end_ts: datetime
    moves: Optional[int] = None
    help_opened: Optional[bool] = None
    time_in_code_panel: Optional[float] = None
    was_correct: Optional[bool] = None
    zone_counts: Optional[Dict[str, Any]] = None

class AttemptCreate(AttemptBase):
    """
    Schema for creating a new attempt. Requires all necessary IDs.
    """
    attempt_id: str
    session_id: uuid.UUID
    user_id: str

class AttemptRead(AttemptBase):
    """
    Schema for reading an attempt from the database.
    Includes fields that are generated by the database.
    """
    attempt_id: str
    session_id: uuid.UUID
    user_id: str
    created_at: datetime

    class Config:
        orm_mode = True

