from pydantic import BaseModel
from typing import Optional, Dict, Any
from datetime import datetime
import uuid

class LearnerFeatureBase(BaseModel):
    """
    Base Pydantic schema for learner features.
    """
    accuracy_history: Optional[Dict[str, Any]] = None
    latency: Optional[float] = None
    error_patterns: Optional[Dict[str, Any]] = None
    help_efficacy: Optional[float] = None
    persistence: Optional[float] = None
    fluency_slope: Optional[float] = None

class LearnerFeatureCreate(LearnerFeatureBase):
    """
    Schema for creating a new learner feature record.
    """
    user_id: str
    session_id: Optional[uuid.UUID] = None

class LearnerFeatureRead(LearnerFeatureBase):
    """
    Schema for reading learner features from the database.
    Includes fields generated by the database.
    """
    id: int
    user_id: str
    session_id: Optional[uuid.UUID] = None
    computed_at: datetime

    class Config:
        orm_mode = True
