from typing import Optional
from enum import Enum
from datetime import datetime

from pydantic import BaseModel


class SexEnum(str, Enum):
    male = 'male'
    female = 'female'
    other = 'other'


class UserBase(BaseModel):
    name: str
    bio: Optional[str] = None
    age: Optional[int] = None
    sex: Optional[SexEnum] = None

    vark_visual_score: Optional[int] = None
    vark_auditory_score: Optional[int] = None
    vark_readwrite_score: Optional[int] = None
    vark_kinesthetic_score: Optional[int] = None


class UserCreate(UserBase):
    # id is generated by Firebase, so the client must supply it here
    id: str


class UserRead(UserBase):
    id: str
    created_at: datetime
    last_updated_at: datetime

    class Config:
        orm_mode = True
