"""Add role to User model

Revision ID: 1bf446bbd0b8
Revises: 7f82c36155a5
Create Date: 2025-06-05 15:06:33.280736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf446bbd0b8'
down_revision: Union[str, None] = '7f82c36155a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1) Add `role` as NOT NULL but give it a default value for all existing rows.
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.String(),
            nullable=False,
            server_default='user'       # <— whatever default makes sense for your app
        )
    )
    # 2) (Optional) If you don’t really want a default going forward,
    #    drop the server_default after populating existing rows:
    op.alter_column(
        'users',
        'role',
        server_default=None
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
