"""create attempts and learner_features

Revision ID: 575df26a0d0d
Revises: f1757a938e91
Create Date: 2025-07-09 09:11:45.487557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '575df26a0d0d'
down_revision: Union[str, None] = 'f1757a938e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempts',
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('puzzle_id', sa.String(), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moves', sa.Integer(), nullable=True),
    sa.Column('help_opened', sa.Boolean(), nullable=True),
    sa.Column('time_in_code_panel', sa.Float(), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('zone_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('learner_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accuracy_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('error_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('help_efficacy', sa.Float(), nullable=True),
    sa.Column('persistence', sa.Float(), nullable=True),
    sa.Column('fluency_slope', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_features_id'), 'learner_features', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learner_features_id'), table_name='learner_features')
    op.drop_table('learner_features')
    op.drop_table('attempts')
    # ### end Alembic commands ###
